[package]
name = "fuzz-honggfuzz"
version = "0.1.0"
authors = ["gyng <gyng@users.noreply.github.com >"]
edition = "2018"

[dependencies]

[target.'cfg(not(target_os = "windows"))'.dependencies]
ferrous-chloride = { path = "../lib" }
honggfuzz = "0.5"
