[package]
name = "fecl"
version = "0.1.0"
authors = ["Yong Wen Chua <lawliet89@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
failure = { version = "0.1.8", features=["backtrace"] }
failure_derive = "0.1.5"
ferrous-chloride = { path = "../lib" }
log = "0.4"
