name: Rust

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node_version: [8, 10, 12]
    steps:
    - uses: actions/checkout@v1
    - name: Fetch
      run: cargo fetch --locked
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
